<?php

namespace AppBundle\Repository;

/**
 * CommandeHistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeHistoriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
