<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository {

    function getCommandesCommentaires($id_commande = null, $limit = 10, $start = 0) {
        $qb = $this->_em->createQueryBuilder()
                ->select("c")
                ->from($this->_entityName, "c")
                ->join('c.commande', "cmd")
                ->orderBy("c.dateCommentaire", "DESC")
                ->setMaxResults($limit)
                ->setFirstResult($start)
        ;
        if ($id_commande) {
            $qb
                    ->where("cmd.id = :id")
                    ->setParameter("id", $id_commande)
            ;
        }
        return $qb->getQuery()->getResult();
    }

}
