<?php

namespace AppBundle\Repository;

/**
 * CouleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurRepository extends \Doctrine\ORM\EntityRepository {

    function couleurDispoPourProduit($reference, $id_taille = null) {
        $qb = $this->_em->createQueryBuilder()
                ->select("DISTINCT c.id")
                ->from("AppBundle:ProduitVariation", "v")
                ->join("v.couleur", "c")
                ->join("v.produit", "p")
                ->where("p.reference = '$reference'")
        ;
        if ($id_taille) {
            $qb
                    ->join("v.taille", "t")
                    ->where("t.id = $id_taille")
            ;
        }
        return $this->_em->createQueryBuilder()
                        ->select("couleur")
                        ->from($this->_entityName, "couleur")
                        ->where("couleur.id IN (" . $qb->getDQL() . ")")
                        ->getQuery()->getResult()
        ;
    }

}
