<?php

namespace AppBundle\Repository;

/**
 * DealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealRepository extends \Doctrine\ORM\EntityRepository {

    function getForAccueil() {
        return $this->getEntityManager()->createQueryBuilder()
                        ->select("d")
                        ->from($this->getEntityName(), "d")
                        ->where("d.active = 1")
                        ->andWhere("d.dateDebut < CURRENT_DATE()")
                        ->andWhere("d.dateFin > CURRENT_DATE()")
                        ->setMaxResults(6)
                        ->getQuery()->getResult()
        ;
    }

}
