<?php

namespace AppBundle\Repository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends \Doctrine\ORM\EntityRepository {

    function getForLayout($limit = 10, $start = 0) {
        return $this->_em->createQueryBuilder()
                        ->select("m")
                        ->from($this->_entityName, "m")
                        ->setMaxResults($limit)
                        ->setFirstResult($start)
                        ->getQuery()->getResult()
        ;
    }

    function countMe() {
        return $this->_em->createQueryBuilder()
                        ->select("COUNT(m)")
                        ->from($this->_entityName, "m")
                        ->getQuery()->getSingleScalarResult()
        ;
    }

    function getForCategorie($id_categorie) {
        return $this->_em->createQueryBuilder()
                        ->select("DISTINCT m")
                        ->from($this->_entityName, "m")
                        ->join("m.categories", "c")
                        ->where("c.id = :id_categorie")
                        ->setParameter("id_categorie", $id_categorie)
                        ->getQuery()->getResult()
        ;
    }

}
