<?php

namespace AppBundle\Repository;

/**
 * ModeLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
