<?php

namespace AppBundle\Repository;

/**
 * ProduitVariationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitVariationRepository extends \Doctrine\ORM\EntityRepository
{
}
